/**
 * Pokedex API
 * API to provide access to the pokedex database
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis


import io.swagger.client.infrastructure.*

class DefaultApi(basePath: String = "https://testing.certant.com/pokedex-api") : ApiClient(basePath) {

    /**
     * is server running?
     * 
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    fun statusGet(): String {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/status"
        )
        val response = request<String>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
