/**
 * Pokedex API
 * API to provide access to the pokedex database
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.LoginBody
import io.swagger.client.models.LoginPostResponse

import io.swagger.client.infrastructure.*

class SecurityApi(basePath: kotlin.String = "https://testing.certant.com/pokedex-api") : ApiClient(basePath) {

    /**
     * Allow a user to be autenticated
     * 
     * @param body  (optional)
     * @return LoginPostResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun loginPOST(body: LoginBody? = null): LoginPostResponse {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/login"
        )
        val response = request<LoginPostResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as LoginPostResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
