/**
 * Pokedex API
 * API to provide access to the pokedex database
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import java.io.Serializable


/**
 * 
 * @param name 
 * @param description 
 */
data class PokemonAbilities (

    val name: String? = null,
    val description: String? = null
):Serializable {
}