/**
 * Pokedex API
 * API to provide access to the pokedex database
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import java.io.Serializable

/**
 * 
 * @param id 
 * @param name 
 * @param lvl 
 * @param evolutionId 
 * @param abilities 
 * @param type 
 * @param image 
 */
data class Pokemon (

    val id: Int? = null,
    val name: String? = null,
    val lvl: Int? = null,
    val evolutionId: Int? = null,
    val abilities: Array<PokemonAbilities>? = null,
    val type: Array<String>? = null,
    val image: String? = null
):Serializable {
}